repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: coverage
        language: system
        pass_filenames: false
        always_run: true
        args:
          - -c
          - |
            coverage run -m pytest tests && coverage report -m

  - repo: local
    hooks:
      # Docstring coverage
      - id: interrogate
        name: interrogate
        entry: uv run interrogate -c pyproject.toml
        language: system
        pass_filenames: false

      # Documentation build test
      - id: mkdocs-build
        name: mkdocs build
        entry: uv run mkdocs build --clean
        language: system
        pass_filenames: false
        files: ^(mkdocs\.yml|docs/)
